### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.model.faster_rcnn.faster_rcnn_HTCN_multi'

### ISSUE THREAD

**Issue by csrwang** [Natlem/M-HTCN#1]
In frcnn_utils.py   from model.faster_rcnn.faster_rcnn_HTCN_multi import _fasterRCNN as frcnn_htcn_m

But, there is no file faster_rcnn_HTCN_multi.

Could you upload this file， thank you.

**Comment by Natlem** [comment]
Oops. Fixed

**Comment by csrwang** [comment]
Thank you very much
