### ISSUE TITLE
about：dataset 

### ISSUE THREAD

**Issue by Y-J-HONG** [Natlem/M-HTCN#4]
it says that ”while FoggyCityscape provides 2500 images for training and 500 for test“  in your paper,however in the foggy cityscapes ,they provide the 3475 images ,so i want to know that which images are you use for training ,can you provide the detail train and test list.
![image](https://user-images.githubusercontent.com/57746629/230114385-1e7b4ae4-e344-4689-b133-65c73766a18e.png)

**Comment by Natlem** [comment]
Oups. Most likely, a typo..  You can follow the original (https://github.com/chaoqichen/HTCN) to prepare the FoggyDataset, I used their exact script to do so.
