### ISSUE TITLE
Some Question about init_frcnn_utils.py

### ISSUE THREAD

**Issue by PX-Xu** [Natlem/M-HTCN#5]
![image](https://github.com/user-attachments/assets/10b7edd8-e8ba-47e1-80cb-d0482c03fbb6)
![image](https://github.com/user-attachments/assets/b00a6e06-e9f6-46fc-8a84-bc60a4a6d799)

I appreciate your fantastic work. I encountered some problems when I reproduced on this project. As shown in this figure, I first try to evaluate the weight that you provided. However, it seems like there are some module(some in init_frcnn_utils.py and distill_frcnn_uitils, traineval_net_HTCN) losses in the code you provided. Could you help me solve these problems?
Hope for your reply as soon as possible.
Best wishes!

**Comment by Natlem** [comment]
Oups, I've uploaded the missing files. It should run now
